version: '2'
services:
  # [TEST]
  golang:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/golang:1.19
    command: ["sleep", "infinity"] # To keep the container running
